### ISSUE TITLE
Seu site de demonstração não pode ser encontrado

### ISSUE THREAD

**Issue by alberto-rj** [hilanasilv/Responsividade#1]
👋 Olá @hilanasilv!

👏 Parabéns por investir seu tempo e levar suas habilidades de front-end para o próximo nível ao construir esse projeto!

Tenho algumas sugestões que poderiam ajudá-la a identificar e resolver o seu problema.

**Como reproduzir o problema:**
1. Acesse a [página principal desse repositório](https://github.com/hilanasilv/Responsividade), ou selecione a aba **"Code"**.
2. Clique no link disponibilizado na seção **"About"**, conforme a imagem a abaixo.
![Link do site de demonstração](https://github.com/hilanasilv/Responsividade/assets/160677568/c27efabc-1072-4930-87f7-99eacc9f880d)
3. Após o clique, provavelmente o erro conforme a imagem a seguir será gerado.
![Erro ao acessar o site de demonstração](https://github.com/hilanasilv/Responsividade/assets/160677568/1ac1724c-6b13-4e64-90fd-712b43022920)

**Como resolver o problema:**
1. Acesse a [página principal desse repositório](https://github.com/hilanasilv/Responsividade), ou selecione a aba **"Code"**.
2. Em seguida, clique no link **"github-pages 5 months ago"**, conforme destacado na imagem abaixo.
![Link](https://github.com/hilanasilv/Responsividade/assets/160677568/946e66eb-bbbc-4b99-82f1-8b9c3e838680)
3. Depois disso, copie o link ilustrado na imagem a seguir para sua área de transferência.
![passo-cpy-link](https://github.com/hilanasilv/Responsividade/assets/160677568/e11729ec-5ad3-4710-80fc-928e6309e3b3)
4. Em seguida, acesse novamente a página principal desse repositório, conforme o passo 1.
5. Na página principal desse repositório, a direita da seção "**About**", clique sobre  o ícone de engranagem, conforme destacado na imagem abaixo.
![passo-settings](https://github.com/hilanasilv/Responsividade/assets/160677568/34ee2bb2-5536-47ef-bd42-abb0a9d8bd7e)
6. Após a abrir a caixa de diálogo, substitui o link encontrado no campo pelo link anteriormente copiado na sua área de transferência.

**Nota:**
- Link encontrado no campo:  `https://hilanasilv.github.io/desafio_aula9/`
![passo-antes](https://github.com/hilanasilv/Responsividade/assets/160677568/ffe20574-9a54-4b6f-a685-ccb6e15af0a6)
- Link copiado na sua área de transferência: `https://hilanasilv.github.io/Responsividade/`
![passo-depois](https://github.com/hilanasilv/Responsividade/assets/160677568/1c9ada74-e84e-4a3e-8baa-1909a4b45743)

7. Após substituir os links, clique sobre o botão **"Save changes"**, conforme ilustrado na imagem a seguir.
![passo-click](https://github.com/hilanasilv/Responsividade/assets/160677568/dfc296ee-d085-4517-ba07-eadd37d2f752)

8. Finalmente, você já poderá acessar o seu ótimo trabalho, clicando no novo link disponibilizado, conforme ilustrado na imagem abaixo.

![passo-link-final png](https://github.com/hilanasilv/Responsividade/assets/160677568/faecfdbe-7a2b-47ae-8a60-194d8d895655)

Então @hilanasilv, essas foram as minhas sugestões para o seu problema. Espero sinceramente que elas possam ajudá-la de alguma forma.

Continue aprendendo, codificando e compartilhando! 🌟
Happy Coding! 🚀

**Comment by hilanasilv** [comment]
Olá @alberto-rj!

Muito obrigada pela sugestão, consegui resolver o problema seguindo seu passo a passo.

Ajudou bastante, vamos juntos! 🚀

**Comment by hilanasilv** [comment]
Olá @alberto-rj!

Muito obrigada pela sugestão, consegui resolver o problema seguindo seu passo a passo.

Ajudou bastante, vamos juntos! 🚀
